### ISSUE TITLE
brightness controls and sleepwake lid

### ISSUE THREAD

**Issue by anishblaze** [RahulRST/Opencore-EFI-for-Dell-Inspiron-5559#1]
the cpu is not going to sleep while lid is down. mainly because you are using old ssdt-pnlf. update the ssdt-pnlf and if still brighness controls not coming up use rehabman brightness fixup alongside

**Comment by RahulRST** [comment]
I have updated the Opencore EFI with the new ssdt-pnlf as you stated and you can grab it in the release v1.0.1 and the installers are available in v1.0.0

**Comment by RahulRST** [comment]
Update me if you have any other issues
